Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
end
