Vagrant.configure("2") do |config|
  config.vm.box = "microsoft/windows10"
  config.vm.box_check_update = false
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  
  config.vm.communicator = "winrm"
  
  config.vm.provision "shell", inline: <<-SHELL
    # Run some shell commands on the Windows VM
    echo "Hello, Windows!"
  SHELL
end
